name: Pruebas y Despliegue Snyk Arreglado1
on: 
  push:
    branches: [ "snyk-fix-5968607f7dc4e0ffdb5a77b0b5b0f41b"]
  pull_request:
    branches: [ "snyk-fix-5968607f7dc4e0ffdb5a77b0b5b0f41b"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout snyk-fix-5968607f7dc4e0ffdb5a77b0b5b0f41b branch
        uses: actions/checkout@v3
        with:
          ref: snyk-fix-5968607f7dc4e0ffdb5a77b0b5b0f41b
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Scan with Sonar
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Johan-Ortega118_cars
            -Dsonar.organization=johan-ortega118
            -Dsonar.branch.name=snyk-fix-5968607f7dc4e0ffdb5a77b0b5b0f41b
  security:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: RunSnyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
  zap_scan:
      runs-on: ubuntu-latest
      needs: security
      name: Run DAST scan on the web application
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: snyk-fix-5968607f7dc4e0ffdb5a77b0b5b0f41b
        - name: ZAP Scan
          uses: zaproxy/action-baseline@v0.6.1
          with:
            docker_name: 'owasp/zap2docker-stable'
            target: 'https://api-johan-ortega118-johan-ortega118.cloud.okteto.net/'
            rules_file_name: '.zap/rules.tsv'
            cmd_options: '-a'

  release:
    runs-on: ubuntu-latest
    needs: zap_scan
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}    
    - name: show linux version
      run: lsb_release -a
    - name: list directory
      run: ls -la
    - name: show python version
      run: python --version
    - name: install dependencies
      run: pip install -r requirements.txt
    - name: make .env 
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_TEST_SECRET_KEY : ${{ secrets.TEST_SECRET_KEY }}
        envkey_TEST_DATABASE : ${{ secrets.TEST_DATABASE }}
        envkey_TEST_USER : ${{ secrets.TEST_USER }}
        envkey_TEST_PASSWORD : ${{ secrets.TEST_PASSWORD }}
        envkey_TEST_HOST : ${{ secrets.TEST_HOST }}
        envkey_TEST_PORT : ${{ secrets.TEST_PORT }}     
        file_name: .env
        fail_on_empty: false  
    - name: show .env file
      run: cat .env
    - name: run tests 
      run: python manage.py test --settings=settings.testing -v 3 --keepdb
    - uses: okteto/context@2.7.0
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    - name: Deploy
      uses: okteto/pipeline@2.7.0
      with:
        name: api-johan-ortega118 # cambiar por su namespace
        timeout: 5m
